#!/bin/bash


if [ ! -f "/scratch/login.cl" ]; then
	ln -s /iraf/login.cl /scratch/login.cl
fi

if [ ! -f "~/.geminidr/rsys.cfg" ]; then
	mkdir ~/.geminidr
	printf "[calibs]\nstandalone = True\ndatabase_dir = ~/.geminidr/" > ~/.geminidr/rsys.cfg
fi

conda init bash

exec "$@"
